name: Wiki Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: Saber2pr/wiki-builder@v0.0.70
        with:
          basename: /zh
          gaId: G-6CLMYWGQBH
          gaAdId: ca-pub-3641373095149503
          gaAdsTxt: google.com, pub-3641373095149503, DIRECT, f08c47fec0942fa0
          gaAdsSlotHtml: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3641373095149503" crossorigin="anonymous"></script><ins class="adsbygoogle" style="display:block; text-align:center;width:100%;height:10rem;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-3641373095149503" data-ad-slot="5932086556"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
          iconUrl: //saber2pr.top/MyWeb/resource/image/saber2pr-top.ico
          i18nConfig: '[{"name":"Chinese","key":"/zh"},{"name":"English","key":"/"}]'
