name: Wiki Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: Saber2pr/wiki-builder@v0.0.52
        with:
          cname: saber2pr.top
          gaId: G-6CLMYWGQBH
          gaAdId: ca-pub-3641373095149503
          iconUrl: //saber2pr.top/MyWeb/resource/image/saber2pr-top.ico
